name: Mixed inputs
defaults:
   run: 
      shell: bash
      
on:
  workflow_dispatch:
    inputs:
      # Input: Choice
      environment_deploy:
        type: choice
        description: Choose Environment
        options:
        - Production
        - Staging
        - Development
        
      # Input: Checkbox  
      fmstatus: 
        type: boolean
        description: fmStatus.json
      appupgrade: 
        type: boolean
        description: appupgrade.json
      flagshipappupgrade:
        type: boolean
        description: flagshipappupgrade.json
      stubflagshipappupgrade:
        type: boolean
        description: stubflagshipappupgrade.json
   
      # Array
      flywheel_adhoc:
        type: boolean
        description: Flywheel Adhoc Files
   
      flywheel_adhoc_files:
        description: "Enter Flywheel Adhoc file/s to upload [file1, file2, ...]"
     
      # Input: Textbox
      confirm_upload:
        description: "Please Confirm Upload by typing [confirm upload]"
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.name }}"

  get-tick: 
    runs-on: ubuntu-latest
    outputs: 
      GH_FILES_TO_UPLOAD: ${{ steps.get_ticked_files_to_upload.outputs.GH_FILES_TO_UPLOAD }}
  
    steps:
    - name: "[ Inputs ] Get files to upload"
      id: get_ticked_files_to_upload
      run: |
      
          # Declare Array Variable
          FILES_TO_UPLOAD=()
          
          if ${{ github.event.inputs.fmstatus }} 
          then
             FILES_TO_UPLOAD+=("fmStatus.json")
          fi
          
          if ${{ github.event.inputs.appupgrade }} 
          then
             FILES_TO_UPLOAD+=("appupgrade.json")
          fi
          
          if ${{ github.event.inputs.flagshipappupgrade }} 
          then
             FILES_TO_UPLOAD+=("flagshipappupgrade.json")
          fi
          
          if ${{ github.event.inputs.stubflagshipappupgrade }} 
          then
             FILES_TO_UPLOAD+=("stubflagshipappupgrade.json")
          fi
          
          # Flywheel 
          if ${{ github.event.inputs.flywheel_adhoc }} 
          then
             # https://www.golinuxcloud.com/bash-split-string-into-array-linux/
             # Change comma (,) to whitespace and add under braces
             myarray=(`echo ${{ github.event.inputs.flywheel_adhoc_files }} | tr ',' ' '`)
             FILES_TO_UPLOAD+=(${myarray[@]})
          fi
          
          # Iterate the loop to read and print each array element
          echo "==================================================================="
          echo "Files to upload"
          echo "==================================================================="
          for value in "${FILES_TO_UPLOAD[@]}"
          do
            echo  $value
          done
          
          
          
          #----------------------------------------------------------------
          # Store to GHA Output
          #----------------------------------------------------------------
          echo "::set-output name=GH_FILES_TO_UPLOAD::${FILES_TO_UPLOAD[@]}" 
          #echo ${FILES_TO_UPLOAD} >> $GITHUB_OUTPUT
          
    - name: "[ Info ] Display all data"
      run: |
         # Iterate the loop to read and print each array element
          echo "==================================================================="
          echo "Files to upload"
          echo "==================================================================="
          for value in ${{ needs.get-tick.outputs.GH_FILES_TO_UPLOAD }}
          do
            echo $value
            case $value in 
               fmStatus.json)
                  target_folder="app/"
                  echo -n "$value :: will be uploaded to smps-in-fm/etc"
                  ;;
               
               appupgrade.json)
                  target_folder="app/"
                  echo -n "$value :: will be uploaded to app/upgrade"
                  ;;
               
               "adhocPromotion"*)
                  target_folder="app/"
                  echo -n "$value :: will be uploaded to app/flywheel/adhoc"
                  ;;
               
               *)
                  echo -n "$value is unknown"
                  ;;
               esac
          done

    - name: "[ Inputs ] Test Message Box"
      run: |
        if [ "${{ github.event.inputs.confirm_upload }}" == "confirm upload" ]
        then
             echo "Let's Upload"
        else 
             echo "cancelled Upload"
        fi
         
    
          
  # ------------------------------------------------------------------------------------------
  # Third Job
  # ------------------------------------------------------------------------------------------ 
  s3_upload:
    name: S3 Upload
    # Run on Group of GHA Runners 
    runs-on: ubuntu-latest
    needs: get-tick
    
    steps: 
    - name: echo
      run: |
         # One Liner Print Code
         echo "${{ needs.get-tick.outputs.GH_FILES_TO_UPLOAD }}"
         
         # Iterate the loop to read and print each array element
          echo "==================================================================="
          echo "Files to upload"
          echo "==================================================================="
          for value in ${{ needs.get-tick.outputs.GH_FILES_TO_UPLOAD }}
          do
            echo  $value
          done
          
