name: Mixed inputs
defaults:
   run: 
      shell: bash
      
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options:
        - monalisa
        - cschleiden
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      fmstatus: 
        type: boolean
        description: fmstatus.json
      appupgrade: 
        type: boolean
        description: appupgrade.json
      flagshipappupgrade:
        type: boolean
        description: app/upgrade/flagshipappupgrade.json
      stubflagshipappupgrade:
        type: boolean
        description: app/upgrade/stubflagshipappupgrade.json
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"

  get-tick: 
    runs-on: ubuntu-latest
  
    steps:
    - name: Get ticked checkbox
      run: |
      
          # Declare Array Variable
          FILES_TO_UPLOAD=()
          
          if ${{ github.event.inputs.fmstatus }} 
          then
             FILES_TO_UPLOAD+=("fmstatus")
          fi
          
          if ${{ github.event.inputs.appupgrade }} 
          then
             FILES_TO_UPLOAD+=("appupgrade")
          fi
          
          if ${{ github.event.inputs.flagshipappupgrade }} 
          then
             FILES_TO_UPLOAD+=("flagshipappupgrade")
          fi
          
          if ${{ github.event.inputs.stubflagshipappupgrade }} 
          then
             FILES_TO_UPLOAD+=("stubflagshipappupgrade")
          fi
          
          # Iterate the loop to read and print each array element
          echo "==================================================================="
          echo "Files to upload"
          echo "==================================================================="
          for value in "${FILES_TO_UPLOAD[@]}"
          do
            echo  $value
          done

          
          
          
          
          
          
        
