name: Mixed inputs
defaults:
   run: 
      shell: bash
      
on:
  workflow_dispatch:
    inputs:
      # Input: Choice
      environment_deploy:
        type: choice
        description: Choose Environment
        options:
        - Production
        - Staging
        - Development
        
      # Input: Checkbox  
      fmstatus: 
        type: boolean
        description: smps-in-fm/etc/fmStatus.json
      appupgrade: 
        type: boolean
        description: app/upgrade/appupgrade.json
      flagshipappupgrade:
        type: boolean
        description: app/upgrade/flagshipappupgrade.json
      stubflagshipappupgrade:
        type: boolean
        description: app/upgrade/stubflagshipappupgrade.json
      
      # ---------------
      environment:
        type: environment
        
      # Array
      flywheel_adhoc_files:
        description: "Enter Flywheel Adhoc file/s to upload"
        default: "file1, file2, ..."
     
      # Input: Textbox
      confirm_upload:
        description: "Please Confirm Upload by typing [confirm upload]"
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.name }}"

  get-tick: 
    runs-on: ubuntu-latest
    outputs: 
      GH_FILES_TO_UPLOAD: ${{ steps.get_ticked_files_to_upload.outputs.GH_FILES_TO_UPLOAD }}
  
    steps:
    - name: Get ticked checkbox
      id: get_ticked_files_to_upload
      run: |
      
          # Declare Array Variable
          FILES_TO_UPLOAD=()
          
          if ${{ github.event.inputs.fmstatus }} 
          then
             FILES_TO_UPLOAD+=("fmstatus")
          fi
          
          if ${{ github.event.inputs.appupgrade }} 
          then
             FILES_TO_UPLOAD+=("appupgrade")
          fi
          
          if ${{ github.event.inputs.flagshipappupgrade }} 
          then
             FILES_TO_UPLOAD+=("flagshipappupgrade")
          fi
          
          if ${{ github.event.inputs.stubflagshipappupgrade }} 
          then
             FILES_TO_UPLOAD+=("stubflagshipappupgrade")
          fi
          
          # Iterate the loop to read and print each array element
          echo "==================================================================="
          echo "Files to upload"
          echo "==================================================================="
          for value in "${FILES_TO_UPLOAD[@]}"
          do
            echo  $value
          done
          
          #----------------------------------------------------------------
          # Store to GHA Output
          #----------------------------------------------------------------
          echo "::set-output name=GH_FILES_TO_UPLOAD::${FILES_TO_UPLOAD[@]}" 
          #echo ${FILES_TO_UPLOAD} >> $GITHUB_OUTPUT

    - name: "Test Message Box"
      run: |
        if [ "${{ github.event.inputs.confirm_upload }}" == "confirm upload" ]
        then
             echo "Let's Upload"
        else 
             echo "cancelled Upload"
        fi
          
       
    
          
  # ------------------------------------------------------------------------------------------
  # Third Job
  # ------------------------------------------------------------------------------------------ 
  s3_upload:
    name: S3 Upload
    # Run on Group of GHA Runners 
    runs-on: ubuntu-latest
    needs: get-tick
    
    steps: 
    - name: echo
      run: |
         # One Liner Print Code
         echo "${{ needs.get-tick.outputs.GH_FILES_TO_UPLOAD }}"
         
         # Iterate the loop to read and print each array element
          echo "==================================================================="
          echo "Files to upload"
          echo "==================================================================="
          for value in ${{ needs.get-tick.outputs.GH_FILES_TO_UPLOAD }}
          do
            echo  $value
          done
          
